### ISSUE TITLE
sql什么时候能够支持智能补全

### ISSUE THREAD

**Issue by mylqf** [apache/incubator-streampark#313]

**Comment by Whojohn** [comment]
ps: 我可以提供一个sql 后端的代码，但是，还需要一个人帮忙开发前端代码才可以，并且不知道该项目是否接收以下实现方式。

方案1：
第一阶段： 基于词频统计的提示 (简单 FST 树+频率实现)。
第二阶段： 上下文输出表补全(利用 calcite 实现)。

方案2：（官方提示不好用）
第一阶段：移植 `Flink sql client` 的 auto complicate 。
