### ISSUE TITLE
[easy to fix list]  good first contributor 

### ISSUE THREAD

**Issue by wolfboys** [apache/incubator-streampark#452]
The following list is the latest newbie tasks (keep up to date). If you are participating in an open source project for the first time, it is recommended to choose one of the following tasks to practice. The first task is used to familiarize yourself with the submission process and feel the friendliness of the community. If you are interested in a task, Please leave a message, for example, I am interested in implementing this task, please submit a PR in 2 weeks if you leave the message. If more than 2 weeks, other contributors are welcome to do it.

**hot to first contribution:** https://github.com/firstcontributions/first-contributions

----

以下是新手任务列表（持续更新中）。如果您是第一次参加开源项目，建议您选择以下任务之一进行练习。第一项任务是熟悉提交过程，感受社区的友好。如果您对某项任务感兴趣，请留言，例如，我对执行此任务感兴趣，如果您留言，请在2周内提交PR。如果超过2周，欢迎其他贡献者参与。

**第一次参与开源**: https://github.com/firstcontributions/first-contributions

**TODO list**

- [x] #980
- [x] #1207
- [x] #1208

<br>

**Comment by Kick156** [comment]
hi @wolfboys ，happy new year🎈，are there any other tasks suitable for making contributions for the first time，I want to have a try。

**Comment by tisonkun** [comment]
Closed as unmaintained.
