### ISSUE TITLE
[Enhancement] Execute Application Mode  on K8s,the job is always in the INITIALIZING state

### ISSUE THREAD

**Issue by xxyykkxx** [apache/incubator-streampark#469]
### Environment Description
* **StreamX Version**:  1.2.0
* **JVM version** (`java -version`):1.8

### Bug Description
when execute application mode on k8s,the job is always in the INITIALIZING state,
but the pod is CrashLoopBackOff,That means the job has failed,
but we can't stop it via streamx,just 

![1637831954(1)](https://user-images.githubusercontent.com/46990259/143415636-f2827e15-cf2b-4882-9351-d08b45eadc00.png)
![1637832650(1)](https://user-images.githubusercontent.com/46990259/143415716-d74c6978-9679-4d9c-ad22-006d1d0f7d6b.png)

**Comment by WilsonWangCS** [comment]
Make sure your service-account is efficient to create pod。and add params like this :
![image](https://user-images.githubusercontent.com/40427110/143428181-8767f3fa-77dd-4a08-87cc-6b423c8ee546.png)

**Comment by xxyykkxx** [comment]
> Make sure your service-account is efficient to create pod。and add params like this : ![image](https://user-images.githubusercontent.com/40427110/143428181-8767f3fa-77dd-4a08-87cc-6b423c8ee546.png)

This problem was solved by pod logs. What I mean is that when a pod exception occurs streamX cannot return the exception result and terminate the program.
You must manually delete deployment via kubectl,then the job can be stoped.
