### ISSUE TITLE
[Bug] Releas v1.2.0 When Project is compiling, click to open the compile log window, no log can be seen, Chrome and Firefox have been tested, no

### ISSUE THREAD

**Issue by xinzhuxiansheng** [apache/incubator-streampark#490]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**: 
* **JVM version** (`java -version`):
* **OS version** (`uname -a` if on a Unix-like system):

### Bug Description（Bug 描述）
请简要、清晰地对您遇到的 Bug 进行描述。

### How to Reproduce（如何重现这个 Bug） 
重现 Bug 现场的步骤，比如：

### Additional context（额外的上下文信息）
添加额外有助于描述该问题的上下文信息，如 JVM 堆栈日志等

### Requirement or improvement（诉求 & 改进建议）
- 请描述您的诉求，或者对此的改进建议

**Comment by WilsonWangCS** [comment]
You can provide some more information here. such as web screenshot about request address and Chrome debug Console

**Comment by xinzhuxiansheng** [comment]
> You can provide some more information here. such as web screenshot about request address and Chrome debug Console



> You can provide some more information here. such as web screenshot about request address and Chrome debug Console

the issue is repeated，please follow up https://github.com/streamxhub/streamx/issues/493
