### ISSUE TITLE
[Bug] Save Point Successed But Task Status don`t changed

### ISSUE THREAD

**Issue by Wilson-BT** [apache/incubator-streampark#496]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version 1.2.0**: 
* **JVM version 1.8**:
* **OS version GNU/Linux** 
* **Flink on K8s for Native-application Mode** 

### Bug Description
![image](https://user-images.githubusercontent.com/40427110/144783335-b004a37a-d515-4fb0-a32d-4b42abc2b451.png)
### How to Reproduce 
If savepoint to cancel the task,the task-status would be changed to ```savepoint``` ,then turn to ```INITIALIZING```. And don`t change again. But the action of savepoint is successful.

**Comment by wolfboys** [comment]
fixed
