### ISSUE TITLE
[Feature] docker supported?

### ISSUE THREAD

**Issue by yuanxingkang** [apache/incubator-streampark#508]
## need docker supported?
any docker compose file?

**Comment by wolfboys** [comment]
This is a great feature, and it is planned to be implemented in subsequent version. If you have a good idea, you are very welcome to contribute.

**Comment by tisonkun** [comment]
We now have

* Docker Compose - https://github.com/apache/incubator-streampark/blob/dev/deploy/docker/docker-compose.yaml
* Helm Chart - https://github.com/apache/incubator-streampark/tree/dev/deploy/helm
